version: '3.8'

services:
    postgres:
        image: postgres:15-alpine
        container_name: agentic-postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: conversation_memory
            POSTGRES_USER: agentic
            POSTGRES_PASSWORD: agentic_dev_password
            POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
        ports:
            - '5432:5432'
        volumes:
            - ./.agentic/postgres-data/data:/var/lib/postgresql/data
            - ./.agentic/postgres-data/logs:/var/log/postgresql
            - ./.agentic/postgres-data/config:/etc/postgresql
        command: >
            postgres
            -c log_destination=stderr
            -c logging_collector=on
            -c log_directory=/var/log/postgresql
            -c log_filename=postgresql-%Y-%m-%d_%H%M%S.log
            -c log_rotation_age=1d
            -c log_rotation_size=100MB
            -c log_min_duration_statement=1000
            -c log_line_prefix='%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h '
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U agentic -d conversation_memory']
            interval: 10s
            timeout: 5s
            retries: 5

    # Future MCP server will be added here
    # mcp-server:
    #   build: ./.agentic/mcp-server
    #   depends_on:
    #     postgres:
    #       condition: service_healthy
    #   environment:
    #     DATABASE_URL: postgresql://agentic:agentic_dev_password@postgres:5432/conversation_memory
    #   volumes:
    #     - ./.agentic/mcp-server:/app
    #   ports:
    #     - "3000:3000"

volumes:
    postgres_data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./.agentic/postgres-data/data
