packages:
    - 'packages/*/*'
    - 'libs/*'
    - 'plugins/*'
onlyBuiltDependencies:
    - '@swc/core'
    - '@vscode/vsce-sign'
    - 'esbuild'
    - 'keytar'
    - 'nx'
    - 'oxc-resolver'
    - 'puppeteer'
    - 'sharp'
